# Site Settings
title:               Mr Darcy
name:                "Mr Darcy"
tagline:             思考、前行
description:         "The blog of Darcy"
baseurl:            #"/Lagrange"
url:                 "http://chaosgsc.com"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Mr Darcy"
  email:             "chaosgsc@gmail.com"
  twitter:           "Ssss74642806"
  instagram:         "acehhhhty"
  github:            "Darcygsc"
  facebook:          ""
  telegram:          ""
  spotify:           ""
  weixin:            ""
  weibo:             ""
  rss:               ""
  dribbble:          "Darcyy"
navigation:
- title: About
  url: /about
- title: Writings
  url: /writings
- title: Books
  url: /books
- title: Friends
  url: /friends

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:
  - jekyll-sitemap
