# Site Settings
title:               Mr Darcy
name:                Mr Darcy
tagline:             思考、前行
description:         "The blog of Darcy"
baseurl:            #"/Lagrange"
url:                 "chaosgsc.com"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Mr Darcy"
  email:             "chaosgsc@gmail.com"
  twitter:           "Ssss74642806"
  instagram:         "acehhhhty"
  github:            "Darcygsc"
  facebook:          ""
  telegram:          ""
  spotify:           ""
  weixin:            ""
  weibo:             ""
  rss:               ""
  dribbble:          ""
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Subscribe
  url: /Subscribe

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
